### ISSUE TITLE
[Idea] How About Replacing Azure Voice With PiperTTS ?

### ISSUE THREAD

**Issue by codecooker1** [t41372/Open-LLM-VTuber#1]
Well I'm currently working a kinda similar project like you and there I'm using the piper  tts for the ai voice.
I actually found this project pretty interesting so I think it would be better to use open source for the tts too.
As piper is optimized forr using on Raspberry pi 4 it shouldn't have a huge performance impact.

<sub>PS. Sorry for the bad english</sub>

**Comment by t41372** [comment]
I'm having some trouble installing PiperTTS on my local machine. There are some problems with piperTTS on macOS right now. I'll probably wait for it to be resolved. 
https://github.com/rhasspy/piper/issues/509
In the meantime, I have edited my garbage code to make adding and switching between TTS models easier.

**Comment by scalar27** [comment]
Not that I understand what he did, I think this person figured it out:  https://github.com/DissonanceTK/MacReddy/commit/5560b21279e17f8c3947fc1c2de2914aa3af2609

**Comment by t41372** [comment]
Looks pretty nice. I'll look into it.

**Comment by t41372** [comment]
PiperTTS models can now be run with `sherpa-onnx` added in `v0.5.0-alpha.2`. https://github.com/t41372/Open-LLM-VTuber/pull/50
We can use Piper now. Just in a different package lol.
