### ISSUE TITLE
change meloTTS voice?

### ISSUE THREAD

**Issue by scalar27** [t41372/Open-LLM-VTuber#10]
I had a lot of fun playing with this today, and appreciate the work you have put into this.  On my M1 Mac, I use llama.cpp (llama-server) and set the port to 11434, and that works well.  Two questions so far:

* Is there a way to change the meloTTS voice?  I like the default but it would be cool to have different options.  I was impressed that the intonation does change a bit with the emotions generated by the LLM, so that is very neat.  The generation is not as fast as piper (I've used with other apps) but the TTS quality is definitely better.

* It seems like it should be easy, but is there a way to run this without invoking the live2d avatar?  I get an error when I try to "python main.py" if server.py is not already running.

thanks!

**Comment by t41372** [comment]
You can change the speaker (and other settings) for meloTTS in `conf.yaml` under the `meloTTS` setting. I don't think there are many options for speakers, though. Check meloTTS [documentation](https://github.com/myshell-ai/MeloTTS/blob/main/docs/install.md) to see the supported languages and speakers.

Yes, you can run this program without using the live2d avatar. Just turn Live2D off under `LIVE2D` setting in `conf.yaml`. I wasn't aware that running this program without a running server would lead to an error if the user didn't change the settings. I just added an error-handling thing. If the server isn't running or any other error happens during the initialization, the program will automatically fall back and proceed without live2d, even if the live2d setting is on.
