### ISSUE TITLE
failed: unable to start container process: exec: "/opt/nvidia/nvidia_entrypoint.sh": stat /opt/nvidia/nvidia_entrypoint.sh: no such file or directory: unknown.

### ISSUE THREAD

**Issue by gg22mm** [t41372/Open-LLM-VTuber#17]
docker pull t41372/open-llm-vtuber

cd www/txsb/api/Open-LLM-VTuber-main/
docker run -it --name vtuber --net=host --rm -v $(pwd)/conf.yaml:/app/conf.yaml -p 12393:12393 t41372/open-llm-vtuber:latest

![图片](https://github.com/user-attachments/assets/3ecdde37-4665-4ccc-905d-1272f27a2527)

[web@localhost Open-LLM-VTuber]$ docker run -it --name vtuber --net=host --rm -v $(pwd)/conf.yaml:/app/conf.yaml -p 12393:12393 t41372/open-llm-vtuber:latest /bin/bash
WARNING: Published ports are discarded when using host network mode
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/nvidia/nvidia_entrypoint.sh": stat /opt/nvidia/nvidia_entrypoint.sh: no such file or directory: unknown.
[web@localhost Open-LLM-VTuber]$

**Comment by t41372** [comment]
Do you have Nvidia container toolkit and GPU passthrough setup?

Can you test this on your computer?

```
sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
```

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/sample-workload.html

Just to make sure you have correctly set up Nvidia container toolkit stuff.
