### ISSUE TITLE
Can I load a custom Live2D model?

### ISSUE THREAD

**Issue by DDXDB** [t41372/Open-LLM-VTuber#2]
By that I mean loading the local model directly without going over the Internet.

**Comment by t41372** [comment]
Not yet, but I am planning to implement this feature

**Comment by t41372** [comment]
Feature implemented. There are some problems though. Documentation is in [doc/live2d.md](https://github.com/t41372/Open-LLM-VTuber/blob/main/doc/live2d.md)
