### ISSUE TITLE
我允许了网页请求的麦克风对话，但是不论怎么说话cmd都没有回应。Uncaught (in promise) AbortError: The user aborted a request.

### ISSUE THREAD

**Issue by AuthourAkson** [t41372/Open-LLM-VTuber#24]
求助，电脑联想y7000p，win11系统，然后在一个求助群中运行成功的哥们是win10系统，没有任何问题，但当我运行项目完毕，允许网页麦克风接入后，不论怎么对话cmd都没有反应，防火墙关了也没用，asr语音模型是large-v3，qwen2.5模型，和那个成功的哥们一致。
![cwutupian](https://github.com/user-attachments/assets/cbe0e056-69cf-4076-b526-973542560fcf)

**Comment by t41372** [comment]
可以给你浏览器的控制台输出截个图吗？在网页里右键检查，说说话，然后给给主控台截个图

**Comment by AuthourAkson** [comment]
好的，没想到佬你竟然半夜在线www
![openaii](https://github.com/user-attachments/assets/26cab228-1dd6-47e6-967a-ab4798ef3832)

**Comment by t41372** [comment]
emmmm 浏览器的麦克风/vad打开失败，不是很懂... 你可以点几下左下角的麦克风按纽看看吗？你是什么时候下载的这个项目？是最新版吗？

**Comment by t41372** [comment]
就随便点几下那个 mic on然后给浏览器控制台截个图，看看他会显示什么。
cmd没有回应是因为前端的麦克风好像没有启动 (要嘛是麦克风没启动要嘛是vad没启动，反正其中一个有问题)，前端根本听不见你说话，所以cmd什么也没接收到。具体原因我不是很清楚 (也没办法在我的电脑上复现你的问题...)

**Comment by t41372** [comment]
另外如果可以的话，你也可以换个浏览器看看会发生什么.... 你也可以检查一下你的浏览器有没有麦克风权限: 开一下这个网站(https://www.vad.ricky0123.com/)，随便说几句话看他能不能听到你(如果听到了，他的方框会加速，等你说完话了会显示刚刚的录音)。

**Comment by AuthourAkson** [comment]
这个网站试过了，能正常录音，mic is on打开后控制台错误也确实变了
![qwe](https://github.com/user-attachments/assets/28872fbc-7329-4b33-8e89-4ada332dac69)
麦克风权限也是开了的
![QQ20241009-103545](https://github.com/user-attachments/assets/9c1c715e-a4dd-4a4b-8bfd-9b554c5f8210)

**Comment by t41372** [comment]
还是麦克风(以及vad模块)无法成功初始化，说实话我真的不知道为什么... 你可以换一个浏览器看看问题是否能复现吗？

我稍微更新了一下网页部分的代码，看能不能获取更多信息。用这个static 文件夹替换掉项目代码文件夹中的 static 文件夹。
[static.zip](https://github.com/user-attachments/files/17302884/static.zip)

另外可以帮我在这个网页控制台中运行下面这两个代码吗?

这个函数会检查麦克风权限在这个网页上是否开启
~~~js
navigator.permissions.query({ name: 'microphone' }).then(function(result) {
    if (result.state === 'granted') {
        console.log("Microphone permission granted");
        init_vad();
    } else if (result.state === 'prompt') {
        console.log("Microphone permission prompt");
        // Handle prompt case
    } else if (result.state === 'denied') {
        console.log("Microphone permission denied");
        // Handle denied case
    }
});
~~~


这个函数会检查 getUserMedia 能不能用
~~~js
if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
    console.log("Browser supports getUserMedia");
} else {
    console.error("Browser does not support getUserMedia");
}
~~~

我说实话我觉得这个问题一点都不科学... 浏览器代码能出个锤子问题，不都是chrome 吗... 我之前传给你的那个 demo网站用的跟我是完全一样的 vad 库，所以根本不应该出问题... 而且这部分的代码(vad 初始化)根本就没有什么出bug 的余地啊... 也没有网络问题因为我把所有的库都放在本地了，没有下载的流程，你断网都能跑... 这个 "Uncaught (in promise): The user aborted a request" 的错误信息也不是很懂... 看了一下可能的原因感觉都不是很像... 而且问题无法复现...

你的chrome 版本是多少？ 我真的不知道还能有那出问题了... 😢

**Comment by AuthourAkson** [comment]
以下是控制台
![QQ20241009-152558](https://github.com/user-attachments/assets/12d85715-3e02-408d-8629-fbc69e15609d)
![QQ20241009-152252](https://github.com/user-attachments/assets/ee3052d3-a8c7-4a90-9f23-50fe5f26c9b7)
同时我的谷歌版本为version129.0.6668.101

**Comment by AuthourAkson** [comment]
google是实时更新的，顺便说一下跑这个项目一共做了哪些工作。我先是装了ffmpeg，cudnn，mpv，并将它们配置到环境变量里，之后又安装了ollama，cmd运行ollama run qwen2.5下载模型，git以前就下好了，开始跑时下载了large-v3的asr模型，最后就是出现了现在的问题

**Comment by t41372** [comment]
说实话我真的不知道你为什么会遇到这个问题。你遇到的问题跟python或是什么ffmpeg 甚至是这个项目的配置都没什么关系，完全只跟浏览器和前端代码有关系，具体来说是浏览器中的麦克风和 vad (Voice Activation Detection) 模型没有办法正常初始化 (报错信息是说初始化被中断了，原因未知)。

vad模型是透过浏览器内的 onnx 环境在浏览器内用 web assembly 运行的，所以不应该会出现平台兼容的问题。上面的demo网站用的是同个版本的同个vad 库，且上面的截图排除了麦克风权限没给和浏览器getMedia api不兼容的问题... 而且模型都在本地，所以也没有什么未知网络环境造成的问题... 而且相同的代码无法在其他电脑上稳定复现... 不是很懂...

我们再试试看改从CDN获取 vad 跟 onnx 运行环境好了。帮我把 `static/index.html`中, 关于 `Voice Activation Detection` 的 部分替换成下面的内容...

~~~html
 <!-- Voice Activation Detection -->
    <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web@1.14.0/dist/ort.js"></script>
    <!-- <script src="libs/ort.js"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/@ricky0123/vad-web@0.0.7/dist/bundle.min.js"></script>
    <!-- <script src="libs/bundle.min.js"></script> -->
~~~

**Comment by AuthourAkson** [comment]
已经修改了，还需要在控制台做什么操作吗

**Comment by t41372** [comment]
看看能不能用，然后截个图，随便点点麦克风按钮之类的

**Comment by AuthourAkson** [comment]
错误也没有发生变化
![QQ20241009-173017](https://github.com/user-attachments/assets/996f45f9-e8fa-4ccf-844d-ba1cd1c80cbd)
mic is on 打开后
![QQ20241009-173159](https://github.com/user-attachments/assets/ad7b8218-2dc2-4358-9e29-8feb92c4427f)

**Comment by t41372** [comment]
换个浏览器试过了吗？我真不知道怎么解决了...

**Comment by AuthourAkson** [comment]
您能看下这个吗，https://github.com/ricky0123/vad/issues/40我是在搜Uncaught (in promise) AbortError: The user aborted a request这个错误时发现的，同时我去看了下原群聊记录，有个跟着操作走的群友最后运行成功但对话的话也没有回应，之后他觉得应该没问题了就没再聊了，我刚与他取得了联系问了下，他的电脑是win10，rtx3080的，所以有可能这是个共性的问题，对方表示等会有时间了再运行下这个项目

**Comment by AuthourAkson** [comment]
https://github.com/ricky0123/vad/issues/40

**Comment by AuthourAkson** [comment]
跟那位群友联系过后，发现对方也一样无法正常回应，以下是对方返图
![3063E8C54ECDDED1DC8F868A1476C97E](https://github.com/user-attachments/assets/848dc392-ef9a-4d9c-8187-bde7fdcf4465)

**Comment by AuthourAkson** [comment]
async function testVAD() {
        try {
            // 请求麦克风访问权限
            const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
            
            console.log('获取到音频流', stream);

            // 初始化VAD
            const vad = new VAD();
           
            // 开始录制（假设你的项目中有类似的方法，将音频流传递给vad处理）
            await vad.start(stream);
          
            console.log('VAD初始化成功');
            // 这里可以添加监听器等其他逻辑来测试VAD的工作情况
            // 例如：vad.on('audio', (data) => { /* 处理音频数据 */ });
        } catch (error) {
            console.error('发生错误:', error);
        }
    }
    testVAD();
在该页面运行以上代码后，能获取的到音频流
![QQ20241009-233955](https://github.com/user-attachments/assets/ef461875-7797-4a56-8c98-fc224fd98d69)

**Comment by t41372** [comment]
你的那位群友遇到的问题跟你不一样，事实上截图里的log显示他前端的vad初始化成功了，如果他有问题可能是其他地方出了问题。

具体获取音频流的那部分是 vad 包处理的，因为他还要跑vad模型判断你有没有在说话，估计是初始化vad模型那部分失败了，但原因未知。

我们试着运行看看vad包官网的代码吧，看能不能运行。你贴的那段 testVAD 写的不太对，所以 VAD is not defined 是在预料之中的。

运行看看这个吧
~~~js
async function main() {
    const myvad = await vad.MicVAD.new({
      onSpeechStart: () => {
        console.log("Speech start detected")
      },
      onSpeechEnd: (audio) => {
        // do something with `audio` (Float32Array of audio samples at sample rate 16000)...
      }
    })
    myvad.start()
  }
  main()
  ~~~

**Comment by AuthourAkson** [comment]
莫名奇妙的，这次运行错误界面变了，you'ke'k有可能是因为我关闭了电脑管家
![屏幕截图 2024-10-10 165341](https://github.com/user-attachments/assets/bec32cd0-6298-4954-9154-a3ca20006be7)
但我又在控制台运行了回复的代码
[
![屏幕截图 2024-10-10 165405](https://github.com/user-attachments/assets/30b278de-8f6f-4a37-8faf-27d94f933e5e)
](url)

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-11 173358](https://github.com/user-attachments/assets/891960ae-4a0e-490d-9921-8e63185c881f)
![屏幕截图 2024-10-11 173602](https://github.com/user-attachments/assets/03280cc5-2c65-4598-9227-0a11484ecca6)
错误变成vad能初始化了却使用不了了，我想顺带问一下调用到vad的python组件叫什么，也就是原代码中
let myvad = null;
        let previousTriggeredProbability = 0; // the possibility that triggered the last speech start
        async function init_vad() {
            try {
                myvad = await vad.MicVAD.new({
                    preSpeechPadFrames: 10,
                    onSpeechStart: () => {
                        console.log("Speech start detected: " + previousTriggeredProbability);
                        if (state === "thinking-speaking") {
                            interrupt();
                        } else {
                            console.log("😀👍 Not interrupted. Just normal conversation");
                        }
                    },
                    onFrameProcessed: (probs) => {
                        if (probs["isSpeech"] > previousTriggeredProbability) {
                            previousTriggeredProbability = probs["isSpeech"];
                        }
                    },
                    onVADMisfire: () => {
                        console.log("VAD Misfire. The LLM can't hear you.");
                        if (state === "interrupted") {
                            state = "idle";
                        }
                        document.getElementById("message").textContent = "The LLM can't hear you.";
                    },
                    onSpeechEnd: (audio) => {
                        if (!voiceInterruptionOn) {
                            stop_mic();
                        }
                        if (ws && ws.readyState === WebSocket.OPEN) {
                            sendAudioPartition(audio);
                        }
                    }
                });
            } catch (error) {
                console.error("Error initializing VAD:", error);
                myvad = null;
            }
        }
是webrtcvad吗

**Comment by t41372** [comment]
python 代码不会直接调用到vad模块。前端网页我是用js写的，透过websocket 协议把录制的音频传回到后端的python服务端。

如果你问的是具体是哪里用到了vad，实际上在初始化这个vad组件(myvad)的时候，所有相关的函数就作为回调函数传进去了。跟vad相关的代码除了启动vad跟关掉vad以外，都在这了。代码中，当 vad检测到人说完话的时候，onSpeechEnd 回调函数会被调用，然后sendAudioPartition函数会被执行，并把音频用 websocket 协议传回到 python服务端去。

你截图中的这个问题... 看起来像是 vad 模型在被初始化成功之前，就开始往后执行了。理论上，除非 `start_mic()` 在短时间内被调用了两次，我不太能想到为什么会出发这个问题，因为vad成功初始化了。我希望你测试的时候，既然vad已经能成功初始化了，就不要再往控制台里贴我之前给你的那些测试代码了，就让整个程序自然的开始。

另外，话说，你现在用的版本是多少？ 0.2.2 到 0.2.3 中间我改了一些浏览器那边的东西。实际上我已经强烈不建议任何人使用 0.2.2 了，因为 0.2.3 我修了个很重要的 bug。另外我上面之前给你发的代码都是给 0.2.3用的，如果用在 0.2.2里面可能会导致未知的后果... 我希望你之前没有把我给你的代码贴到 0.2.2版本的软件里面...

还有，为什么他忽然就能初始化 vad 了？你改了什么东西吗？是因为电脑管家的原因吗？你可以稍微测试一下吗？我有点好奇。是不是电脑管家封锁了本地网页的麦克风权限？或是... 算了我猜不出来，随便啦。

(你可能透过观察我的前端代码能发现，其实我前端写的挺屎的... 我最近学了react + typescript还有一些比较正规的前端开发的方式, 在未来大概率会把整个前端代码用react重写一遍，但这会拖得比较久)

**Comment by t41372** [comment]
测试的时候让程序自然的开始，当小人出现的时候随便说几句话，看看控制台里有没有反应 (正确的反应是他会在你开始说话时发现你在说话，然后在你说完话的时候喷一个数组到控制台里。此时音频就已经被传回后端了，如果还有问题，记得也给后端的log截个图)

**Comment by AuthourAkson** [comment]
怎么说呢，成功初始化的原因我感觉也有可能是因为更新了电脑系统，在电脑重启更新完毕后，我打开电脑抱着电脑管家会不会妨碍本地脚本运行的想法又是运行了一次，然后就变成了这样，但又试了试后猜测应该不是电脑管家的问题，因为再次打开电脑管家它的错误依然是上图的样子。
    至于版本的问题，先前已经说过了，我用的是最新版的(10.5号时下的)，之后我也怀疑是版本问题便找了完全成功运行的群友要了他的版本(0.2.2),但是实际运行后出错都相同没有任何区别。
   我嘞个，当你看到这句话，已经是打完上面两段话十分钟后了，我已经知道为什么会出现之前的Aborterror了，当我试着关掉麦克风权限再打开时，Aborterror又出现了，然后谷歌莫名其妙将页面上的字自动翻译成中文，我直接关了再重新打开这个模型，错误
就变成了上图的样子。
  下图为控制台测试画面，顺便说一下，多次点击mic is on后，发现页面上方会出现的暂停的按钮也消失了，但点击后也没有错误出现了。
![屏幕截图 2024-10-11 195044](https://github.com/user-attachments/assets/3d61c721-7e21-4cb0-afcf-a7b9b7da81ef)

**Comment by AuthourAkson** [comment]
有一点说的不太清，我是直接让谷歌翻译直接忽略了这个网站，然后才关闭再打开模型就好了，两个版本都一样，当关闭再开启麦克风权限后点击reload website to update settings就出现了aborterror。

**Comment by AuthourAkson** [comment]
emm回应的问题到现在还是没法解决，说话依旧不回应，控制台日志还是和上一个回复中的的一样

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-16 003134](https://github.com/user-attachments/assets/4786df11-0bdd-4757-a286-59238139ef79)
我又跟成功的群友对比了一下，发现libs库里的文件系统识别不到，有没有可能是因为这个错误导致的

**Comment by t41372** [comment]
我们可以试试。
你把 `static/index.html` 里面的 `<head>` 元素 改成这个

```html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Open-LLM-VTuber</title>

    <!-- pixi live2d dependencies -->
    <!-- Load Cubism and PixiJS -->
    <script src="https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js"></script>
    <!-- <script src="libs/live2dcubismcore.min.js"></script> -->
    <script src="https://cdn.jsdelivr.net/gh/dylanNew/live2d/webgl/Live2D/lib/live2d.min.js"></script>
    <!-- <script src="libs/live2d.min.js"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/pixi.js@7.x/dist/pixi.min.js"></script>
    <!-- <script src="libs/pixi.min.js"></script> -->

    <script src="https://cdn.jsdelivr.net/gh/RaSan147/pixi-live2d-display@v0.5.0-ls-7/dist/index.min.js"></script>
    <!-- <script src="libs/index.min.js"></script> -->



    <script src="TaskQueue.js"></script>

    <!-- Voice Activation Detection -->
    <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web@1.14.0/dist/ort.js"></script>
    <!-- <script src="libs/ort.js"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/@ricky0123/vad-web@0.0.7/dist/bundle.min.js"></script>
    <!-- <script src="libs/bundle.min.js"></script> -->

    <link rel="stylesheet" href="index.css">
</head>
```

**Comment by t41372** [comment]
另外你检查一下你的电脑管家或杀毒软件之类的，看看他们有没有莫名其妙封锁了什么requests...

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-16 211801](https://github.com/user-attachments/assets/01b3ef15-3c76-4be8-a152-328369f33d4e)
![屏幕截图 2024-10-16 211825](https://github.com/user-attachments/assets/20b251ae-ed62-4f40-b34b-8ac0061f8b58)
似乎就是组件识别不到的问题。。。

而且我也不知道电脑管家在哪里看封锁了哪些request

**Comment by AuthourAkson** [comment]
啊我刚又看了下代码，发现之前复制粘贴你的那段没保存，保存后之前的报错都消失了，但是依旧无法录音，剩下关于onnxruntime的警告报错，还记得我先前说的运行成功但同样无法对话的win10水友吗？现在我的控制台界面和他一样了，现在只要修复onxx环境的这个问题就可以了。
这是我的截图
![屏幕截图 2024-10-17 010603](https://github.com/user-attachments/assets/bb18e48b-beba-45fc-9225-65e0904d9a39)
那位win10水友的
![3063E8C54ECDDED1DC8F868A1476C97E](https://github.com/user-attachments/assets/44e65dcf-4268-443f-b405-435659acb55c)

**Comment by t41372** [comment]
这个黄色的 warning 是正常的，这个黄色的警告信息不是造成问题的原因。

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-18 031816](https://github.com/user-attachments/assets/5be6caa9-398b-4179-8aee-540ac01fbed2)
我又试了一次vad的demo看是不是vad本身的问题，结果发现demo录音不了了，并出现了“跨区域隔离错误”的警告
![屏幕截图 2024-10-18 031834](https://github.com/user-attachments/assets/480b2f85-32fb-4ad1-a3da-0bdf80ce3baf)

**Comment by t41372** [comment]
呃，你之前不是说demo网站可以正常录音吗... 为什么现在又不行了？有什么发生变化了吗？
但那个 warning 不是你无法录音的原因。我也有那个 warning，但我可以录音。
不过如果 demo 网站无法录音的话，基本可以确定不是我的代码的问题了。

你检查一下你 chrome 用的是什么麦克风，确认一下你的 chrome 的音频输入没有问题。我怀疑你 chrome 用的麦克风不对。也有可能你的电脑管家封锁了麦克风的权限？
你可以用这个网站测试一下你的麦克风正不正常。
https://webcammictest.com/check-mic.html

**Comment by AuthourAkson** [comment]
试过了也是用不了，录完音后打开播放并没有声音，但是麦克风我也确认确实打开了

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-18 130443](https://github.com/user-attachments/assets/6e1f9b3e-0cc3-4a1d-91cc-ef411974dd8c)
这是录音时的控制台

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-18 130633](https://github.com/user-attachments/assets/2984c1a3-6375-4f43-b540-352d3e8d66c8)
用的就是电脑自带的麦克风列阵

**Comment by t41372** [comment]
控制台里的记录没有任何问题。你的麦克风的声音传不到浏览器。
这应该是麦克风或是音频设备的问题了。确认你选择的音频输入设备是正确的麦克风，在你的Windows 设置中检查你的麦克风，确认你电脑中的录音软件真的能听到你说话的声音，具体你可以跟AI 聊聊看怎么解决，我也没那么懂 Windows 的麦克风所以我也不好帮你解决。

**Comment by t41372** [comment]
点错了

**Comment by AuthourAkson** [comment]
卧槽运行了，之前的声卡被我给改了，改回来后再运行时说话没反应，然后我点了mic is on后就成功运行了，但是控制台又报了新的错误，弹出错误一小会后cmd就自动关了，以下为截图
![屏幕截图 2024-10-18 204236](https://github.com/user-attachments/assets/70a3f8be-f4a0-4d6e-9944-a5abd1678cdd)

**Comment by t41372** [comment]
你用的是 `faster-whisper` 吗？参考这个 issue。
https://github.com/SYSTRAN/faster-whisper/issues/575
你可以试试它的解法，或是干脆改用 FunASR + SenseVoiceSmall 来做语音识别。

**Comment by AuthourAkson** [comment]
emm这个issue里的链接就是fater-whisper的github网址，所以实际上这个issue并没有解决方法
也不知道是不是我设置的问题，设置界面如下
![屏幕截图 2024-10-19 123924](https://github.com/user-attachments/assets/66be79d5-ae33-46c4-bcf5-8c7666fe7302)

**Comment by t41372** [comment]
可以试试 `nvidia-smi` 命令看看你的cuda版本是不是12吗？
他的那个requirements 页面上有写不支持cuda 11，如果你是cuda 11 的话可以试试 `pip install --force-reinstall ctranslate2==3.24.0` 。

**Comment by AuthourAkson** [comment]
我直接从别的网站下载了cublaslt64_12.dll,程序具体期望cuda库目录的路径是什么

**Comment by AuthourAkson** [comment]
对了我看了下，我的cuda版本是12.2

**Comment by t41372** [comment]
我不知道啊朋友，这是Windows+N卡cuda驱动的问题，我用mac和Linux的不用这玩意儿啊...

话说，你有装cuBLAS for CUDA 12 和cuDNN 8 for CUDA 12吗？faster-whisper的页面上说要装... 看你缺的这个文件长的也挺cuBLAS的...

要不你用FunASR或是把faster-whisper的device改成CPU试试吧，Windows相关的驱动问题太复杂了，我Readme都直接让用Windows的用wsl了...

**Comment by AuthourAkson** [comment]
改成funasr后又出错了，而且SenseVoiceSmall具体readme里没有说具体配置操作
![屏幕截图 2024-10-19 204220](https://github.com/user-attachments/assets/c58be334-a847-43f8-b5cc-aba90a4b38f9)
以下是设置
![屏幕截图 2024-10-19 204427](https://github.com/user-attachments/assets/0954891b-cf0f-403c-9893-050ee803386e)

**Comment by AuthourAkson** [comment]
尝试faster-whisper改成cpu运行后cmd一直回复interrupted
![屏幕截图 2024-10-19 205009](https://github.com/user-attachments/assets/a6fb3cd8-3942-4d8f-b5eb-95ceb97a914d)
![屏幕截图 2024-10-19 205040](https://github.com/user-attachments/assets/d2473680-2df7-40ef-a0dc-2915e4ef9bb2)
![屏幕截图 2024-10-19 205048](https://github.com/user-attachments/assets/7c1cf7d4-b2f5-4e42-84d7-2a87681170e9)
![屏幕截图 2024-10-19 205657](https://github.com/user-attachments/assets/1c38f04e-847a-41dd-9b9c-a132ce1648a0)

**Comment by AuthourAkson** [comment]
刚chon重新打开我又点了点旁边的interruption on，发现莫名其妙的录上了，但是上面显示录上的话时，已经是我说完这句话的七八秒后了，而且也出现了错误
![屏幕截图 2024-10-19 210334](https://github.com/user-attachments/assets/777dd48b-d8f1-47ee-8ba8-c4dc26b553ae)

**Comment by AuthourAkson** [comment]
![Screenshot_20241020_163445](https://github.com/user-attachments/assets/c939a45a-6915-4ce7-bdc3-f0a71f72dba2)
以上就是我下载配置的东西，我并不觉得缺了些什么。。。

**Comment by AuthourAkson** [comment]
成功了，我去使用cudatoolkit更新了cuda至12.6版本，自动将缺失的包cuBlAS补齐了，asr语音也识别到了我说的话，但是又出了新错误，不知道为什么模型的回复是空的
![屏幕截图 2024-10-20 175646](https://github.com/user-attachments/assets/182780a9-f839-40ac-9d0c-e2a3f65e31a4)

**Comment by AuthourAkson** [comment]
识别到的文本不知道为什么发不到qwen2.5模型上

**Comment by t41372** [comment]
报错信息说你本地没有qwen2.5:7b的模型。你用的是ollama吗？qwen2.5:7b有下载到本地吗

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-20 180651](https://github.com/user-attachments/assets/bc372cc6-6d84-43d1-8829-23a802d177e6)
我确定它部署了，而且这个错误再看一下，它似乎把我的qwen2.5模型识别成了“qwen2.”模型？

**Comment by t41372** [comment]
ollama list一下检查下名字。让我猜猜，你本地的模型名字是不是叫做qwen2.5:latest，而不是qwen2.5:7b？

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-20 181704](https://github.com/user-attachments/assets/31b7744e-4f67-4f31-8804-21610e47342c)
好像还真是，但我是照着群友配的，他设置成qwen2.5:7b可以正常运行

**Comment by t41372** [comment]
那是因为他本地有qwen2.5:7b。虽然`qwen2.5:7b`跟`qwen2.5:latest`实际上是一个模型，但你拉取的时候用的那个名字就是你模型的名字，别乱改。你本地只有叫做`qwen2.5:latest`的模型，没有叫做`qwen2.5:7b`的模型。
你可以让你群友跑一下`ollama list`，看看他是不是有 `qwen2.5:7b`，然后可以自己跑一下看看你是不是没有。

**Comment by AuthourAkson** [comment]
它能正常回答了，但是没有音频回复
![屏幕截图 2024-10-20 202409](https://github.com/user-attachments/assets/302ed7f2-f107-409d-8266-90da7042d237)
![屏幕截图 2024-10-20 202419](https://github.com/user-attachments/assets/444a70be-a5b3-44bb-977d-5335c924961e)
![屏幕截图 2024-10-20 202537](https://github.com/user-attachments/assets/0d441470-3061-4092-85b0-c18c1a973439)

**Comment by t41372** [comment]
如果你能用wsl的话，我推荐你放在wsl里跑... Windows莫名其妙的问题太多了...

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-20 204226](https://github.com/user-attachments/assets/0db696d5-d21d-44c7-a5a3-f96948d2c5a4)
用的就是edge-tts

**Comment by t41372** [comment]
给你浏览器的控制台截个图，我确认一下是后端没发送音频而不是前端发了音频没拨放

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-20 205521](https://github.com/user-attachments/assets/4b539e08-bfbc-4ad3-ba1e-97907d9d74c7)

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-20 205749](https://github.com/user-attachments/assets/aebbcd87-c928-403c-b1cd-a510632b0dd9)
还有这个，不知道怎么回事，一开VPN就出现了

**Comment by t41372** [comment]
你下面那张图的报错跟vpn可能没关系，他说的是在跑语音识别的时候爆显存了。

至于你试试在你的python 环境中，命令行试试 `edge-tts --text "Hello, world!" --write-media hello.mp3` 看能不能生成出音频文件

**Comment by AuthourAkson** [comment]
![屏幕截图 2024-10-20 211120](https://github.com/user-attachments/assets/d391c923-2d0b-4298-ae57-f3ed1c49ae3a)

**Comment by t41372** [comment]
？
？？？
你能联网吗？你是断网环境吗？

**Comment by AuthourAkson** [comment]
我是连了网的，以前运行过edge-tts "Hello, world!" --text，当时它都能生成语音的

**Comment by AuthourAkson** [comment]
等下，你让我刚才运行这段指令是要在项目打开的情况下运行吗

**Comment by t41372** [comment]
不是啊，你检查一下你vpn有没有把你网弄炸，这个edge-tts应该不用翻墙的。如果你不想弄这个，meloTTS，cosyVoice之类的运行的时候不用网(不过你显存好象不太够用...)，你可以配一下。
话说你居然没有用虚拟环境吗？你没看我文档吗... 不用虚拟环境以后可能会遇到莫名其妙的问题的... 不过算了，不重要。

**Comment by AuthourAkson** [comment]
因为我自己虚拟环境什么的都没搞过就没去开了，而且docker之前都下过了，怎么在wsl上跑我也不知道该怎么做

**Comment by AuthourAkson** [comment]
我寻思电脑8g显存，5.8g的qwen模型，4.2g的语音asr模型两个并不是同时进行的为什么总会溢出

**Comment by t41372** [comment]
因为模型会在显存里待一段时间... 把模型从硬盘里加载到显存里其实挺耗时间的，你可以考虑一下你的硬盘读取速度，如果每次运行都要把显存里的模型清掉，那你每次说话到LLM反应的延迟会从毫秒变成好几秒甚至几十秒...

**Comment by t41372** [comment]
反正你现在遇到的问题是因为edge-tts是要联网的，他连不上网，所以炸了。你可以考虑是要解决你网的问题还是换一个不用联网的。

**Comment by AuthourAkson** [comment]
我搞不懂为什么会连不上网，之前运行edge-playback --text "Hello, world!"它都可以显示在哪里路径产生文件，并调用mpv来播放语音的

**Comment by t41372** [comment]
不知道捏。问问群友？问问AI？重开机解君忧？

**Comment by AuthourAkson** [comment]
我勒个，终于成了，只不过回复的有点慢，问一句话到回复以及音频播放要30s左右
好像还真是VPN的问题，不过好像也有版本的问题，更新了edgetts后并关闭了vpn才彻底解决
然后就是之前测试的时候舍友打go，吵的总是导致inturrupted连续出现的问题
然后就是这个录音vad的问题，vad初始化错误其实到现在也没解决，只不过每次打开点击mic按钮两次再打开就能莫名奇妙录制了

**Comment by AuthourAkson** [comment]
我勒个，终于成了，只不过回复的有点慢，问一句话到回复以及音频播放要30s左右
好像还真是VPN的问题，不过好像也有版本的问题，更新了edgetts后并关闭了vpn才彻底解决
然后就是之前测试的时候舍友打go，吵的总是导致inturrupted问题连续出现
以及这个录音vad的问题，vad初始化错误其实到现在也没解决，只不过每次打开再点击mic按钮两次后等mic start就能莫名奇妙的开始录制了

**Comment by t41372** [comment]
vad 库的作者几个小时前刚更新了，你把 `static/index.js` 文件中的 Voice Activation Detection 那部分改成下面这段代码来升级，然后看看 vad 的问题还在不在。

```javascript
<!-- Voice Activation Detection -->
<script src="https://cdn.jsdelivr.net/npm/onnxruntime-web@1.19.2/dist/ort.js"></script>
<!-- <script src="libs/ort.js"></script> -->
<script src="https://cdn.jsdelivr.net/npm/@ricky0123/vad-web@0.0.19/dist/bundle.min.js"></script>
<!-- <script src="libs/bundle.min.js"></script> -->
```

**Comment by t41372** [comment]
如果你想避免被舍友的声音打断，你可以把语音打断的功能关掉 (Voice Interruption 按钮)。

速度慢的离谱的话可能还是显存。我印象中 Ollama 如果显存不够，会把一些东西放到RAM上去 (在mac上会放到swap去)，虽然不会炸，但会慢的离谱。

或许你可以用小一些的模型，或是用量化程度高一些的qwen2.5 7b，比如 `qwen2.5:7b-instruct-q3_K_M` 或是 `qwen2.5:7b-instruct-q4_K_M`。
如果性能瓶颈在语音识别上的话，可以考虑用小一些的 `distil-large-v3` 或 `medium`，或是用FunASR 的 SenseVoiceSmall模型，中文水平很不错。

虽然现在说可能有些晚，但如果你不介意 LLM 和 语音识别 用API的话，groq 的 api 不用钱，注册不用信用卡不用手机号，每天都有很慷慨的免费额度，而且速度巨快。Groq 的 LLM 跟 ASR 我都做了适配。(不过我不知道在墙内能不能愉快的用groq就是了)

**Comment by t41372** [comment]
如果没别的问题的话，我就把issue关了。
