### ISSUE TITLE
Can we add Distil-whisper?

### ISSUE THREAD

**Issue by FerLuisxd** [t41372/Open-LLM-VTuber#25]
[Distil-whisper](https://github.com/huggingface/distil-whisper) is apparently the fastest whisper implementation (from the guy that created whisper JAX), and runs on the CPU, it could be nice to see it here!

Also openai just released the [turbo model for whisper](https://github.com/openai/whisper/discussions/2363)

**Comment by t41372** [comment]
The faster whisper option in ASR option can run distilled whisper. In fact this project (Open-LLM-VTuber) runs distilled-whisper medium English only version by default, and there are many other models you can use with faster whisper.

I believe there are some work being done recently on using the new turbo model with faster whisper. I actually think there are people gotten it to work if my memory is correct. Maybe once all of those are on a more stable condition, we can update the documentation to reflect those news.

**Comment by t41372** [comment]
I also have the original openai whisper binding support in this project, so I guess you can just update the package, download the turbo model and it will probably work.
