### ISSUE TITLE
请问这是为啥呀

### ISSUE THREAD

**Issue by seetimee** [t41372/Open-LLM-VTuber#26]
![image](https://github.com/user-attachments/assets/09d97937-8a19-41a7-ae71-4388f4bb1eda)
![image](https://github.com/user-attachments/assets/4c2a1ce3-e351-4f6d-9984-d16edb14b74b)

**Comment by t41372** [comment]
具体问题要看你浏览器的控制台里写了什么。不过根据你浏览器访问的ip来看，如果你要在非本地运行服务端，在另外一台电脑上开启网页，你要上https (因为麦克风不能在不安全环境里启动，这是浏览器的限制)，而且上完https后要在 `conf.yaml` 里面顶部把 `PROTOCOL` 改成 `https://` 。 (这是我最近才知道的，所以文档没更新，抱歉...)

**Comment by seetimee** [comment]
可是我的浏览器已经把该ip加入白名单了

**Comment by seetimee** [comment]
![image](https://github.com/user-attachments/assets/924b5582-e8c7-4ba5-b48b-33ac6d74ca44)

**Comment by seetimee** [comment]
我再试下用frp转发到本地

**Comment by t41372** [comment]
那我建议你给浏览器控制台截个图，不然我也不知道它具体是出了什么问题...
浏览器控制台: 右键 -> 检查 -> 主控台/控制台
那里有网页相关的log

**Comment by seetimee** [comment]
![image](https://github.com/user-attachments/assets/6caad009-c674-4772-9a8c-0b5fa85490e1)
(✪ω✪)

**Comment by seetimee** [comment]
换了三个浏览器,好像谷歌浏览器可以连上

**Comment by seetimee** [comment]
谷歌加入白名单后终于成功了，原来是浏览器的问题，辛苦hub主了o(╥﹏╥)o
