### ISSUE TITLE
xTTS issue

### ISSUE THREAD

**Issue by mattfro** [t41372/Open-LLM-VTuber#29]
Trying to use xTTS it seems to have problem to write to file, I get this always:
expected str, bytes or os.PathLike object, not UUID Producer stopped

in xTTS.py file, I change this:  file_name = file_name_no_ext
to: file_name = f"{file_name_no_ext}.wav"

it works, but it just saves a lot of files on the root folder of Open-LLM-VTuber and does not remove them afterwards.

I use the latest version

**Comment by t41372** [comment]
Fixed it
