### ISSUE TITLE
xTTS path issue on windows

### ISSUE THREAD

**Issue by mattfro** [t41372/Open-LLM-VTuber#30]
I get this with latest when testing it on windows:
[Errno 2] No such file or directory: './cache\\598360a3-28bc-44a7-b637-25a06115274f.wav' Producer stopped

Seems when changing this in xTTS.py:
        self.new_audio_dir = "./cache"
to
        self.new_audio_dir = ".cache/"

fixes it at least on windows. But not sure if that works in linux then, I haven't tested that

**Comment by t41372** [comment]
I think I fixed it in commit 36ac83d, but I havn't got the chance to test it on Windows.
