### ISSUE TITLE
is_complete_sentence(char) in main.py

### ISSUE THREAD

**Issue by miivalj** [t41372/Open-LLM-VTuber#31]
Commit https://github.com/t41372/Open-LLM-VTuber/commit/9880a7f570253a45a90065d6e4e78a2906ab7567  appears to conflict with the intended functionality of the `is_complete_sentence` method. 

Currently `speak_by_sentence_chain` splits "I am Mr. Smith" into two sentences, which disrupts the intended flow of speech.

**Comment by t41372** [comment]
You know what? You are absolutely correct. Apparently I was thinking about optimization but didn't really know what I was doing. Thank you for catching that.
