### ISSUE TITLE
requirements.txt可能需要更新

### ISSUE THREAD

**Issue by yeziyezi** [t41372/Open-LLM-VTuber#46]
main分支ada4b提交，在执行```python start_cli```和```pip install -r requirements.txt``` 之后，执行```python server.py```会报错缺少 ```torch```  ```funasr``` ```torchaudio``` 这三个依赖，可能需要补充到requirements.txt中

**Comment by t41372** [comment]
使用 `start_cli` 和 `start_webui` 等一键安装模式，不应该执行 `server.py`，因为 `server.py` 并不会激活 `start_cli` 和 `start_webui` 等启动脚本所创建的miniconda 环境。
目前文档正在整理... 不过有人已经做了相关视频，关于一键安装脚本 (`start_cli.py` 和 `start_webui.py`) 的使用 可以参考 https://www.bilibili.com/video/BV1UDz4YcEr8/
