### ISSUE TITLE
looking for more contributors?

### ISSUE THREAD

**Issue by Vinventive** [t41372/Open-LLM-VTuber#48]
I can contribute to this project. I have experience integrating real-time vision input with LLMs - see my previous work, [AIVisionCompanion](https://github.com/Vinventive/AIVisionCompanion), as a reference. Additionally, I recently learned how to create a secure, standalone, portable Windows build (inspired by the Portable Version of ComfyUI) that does not require end users to have an existing Python environment installed with all required dependencies configured on their systems.

My main focus could be integrating real-time vision input into the local version of the project (to prioritize personal privacy) and assisting in creating an easy, plug-and-play distribution for users who are unfamiliar with setting up Python environments and managing dependencies.

Let me know if I should create a new fork or simply start adding PR's.

**Comment by t41372** [comment]
Hi,

Thank you so much for reaching out and offering to help! Apologies for the delayed response.

It would be incredibly helpful and greatly appreciated if you could assist with integrating real-time vision input capability. I'd love to offer any help for you to bring this feature to life!

I do want to let you know that the project is undergoing a significant refactoring:
- The backend is being almost entirely rewritten on the `superb-refactoring` branch.
- The front end has been completely reworked by @ylxmf2005 in the [Open-LLM-VTuber-Web](https://github.com/t41372/open-llm-vtuber-web) repository with React, TypeScript, Vite, and ChakuraUI. A placeholder camera window has been added. However, no backend support for real-time vision has been implemented yet.

A PR would be fantastic, especially if it builds on the `superb-refactoring` branch and aligns with the new front end. 

I'm more than happy to discuss the details of the implementation and provide any support you might need along the way.

Looking forward to hearing your thoughts—thank you again for your willingness to contribute!

**Comment by t41372** [comment]
I'm very interested in the standalone build. The current plan is to create a GitHub Actions workflow to package everything on each release. Any thoughts or contributions are greatly appreciated.

**Comment by Vinventive** [comment]
> Hi,
> 
> Thank you so much for reaching out and offering to help! Apologies for the delayed response.
> 
> It would be incredibly helpful and greatly appreciated if you could assist with integrating real-time vision input capability. I'd love to offer any help for you to bring this feature to life!
> 
> I do want to let you know that the project is undergoing a significant refactoring:
> 
> * The backend is being almost entirely rewritten on the `superb-refactoring` branch.
> * The front end has been completely reworked by @ylxmf2005 in the [Open-LLM-VTuber-Web](https://github.com/t41372/open-llm-vtuber-web) repository with React, TypeScript, Vite, and ChakuraUI. A placeholder camera window has been added. However, no backend support for real-time vision has been implemented yet.
> 
> A PR would be fantastic, especially if it builds on the `superb-refactoring` branch and aligns with the new front end.
> 
> I'm more than happy to discuss the details of the implementation and provide any support you might need along the way.
> 
> Looking forward to hearing your thoughts—thank you again for your willingness to contribute!

Thank you for your reply. Thanks for informing me about the refactoring. It will save me both time and confusion. I’ll check out the `superb-refactoring` branch. 

> I'm very interested in the standalone build. The current plan is to create a GitHub Actions workflow to package everything on each release. Any thoughts or contributions are greatly appreciated.

Given the size of your project, we may face challenges fitting it under GitHub’s 2GB upload limit as a standalone file. I will explore possible solutions in my free time.
